name: CI

on:
  push:
    tags:
      - alpine-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "alpine-(.*)"

      - name: Version name based on tag
        run: |
          echo "GIT_TAG_NAME=${GIT_TAG_NAME}"
          echo ${{ steps.tagName.outputs.tag }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          path: ./alpine/${{ steps.tagName.outputs.tag }}
